# Generated by Django 6.1 on 2026-08-19 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=40, unique=True)),
                ('customer_name', models.CharField(max_length=120)),
                ('mobile', models.CharField(db_index=True, max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.JSONField(default=dict)),
                ('subtotal', models.PositiveIntegerField()),
                ('shipping_charge', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField()),
                ('order_status', models.CharField(choices=[('AWAITING_PAYMENT', 'Awaiting Payment'), ('PAID', 'Paid'), ('PROCESSING', 'Processing'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='AWAITING_PAYMENT', max_length=40)),
                ('payment_status', models.CharField(choices=[('NOT_CONFIGURED', 'Not Configured'), ('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='NOT_CONFIGURED', max_length=40)),
                ('shipment_status', models.CharField(choices=[('NOT_CREATED', 'Not Created'), ('CREATED', 'Created'), ('AWB_ASSIGNED', 'Awb Assigned'), ('SHIPPED', 'Shipped'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out For Delivery'), ('DELIVERED', 'Delivered'), ('RETURNED', 'Returned')], default='NOT_CREATED', max_length=40)),
                ('tracking_token', models.CharField(blank=True, max_length=64, unique=True)),
                ('shiprocket_order_id', models.CharField(blank=True, max_length=80)),
                ('shiprocket_shipment_id', models.CharField(blank=True, max_length=80)),
                ('shiprocket_awb', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('price_inr', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('stock_quantity', models.PositiveIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=180)),
                ('unit_price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('line_total', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.guestorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product')),
            ],
        ),
    ]
