# Generated by Django 6.1 on 2026-08-20 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_seed_catalogue'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestorder',
            name='checkout_idempotency_key',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='guestorder',
            name='courier_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='guestorder',
            name='courier_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='guestorder',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guestorder',
            name='integration_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='guestorder',
            name='label_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='guestorder',
            name='last_tracking_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guestorder',
            name='manifest_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='guestorder',
            name='payment_order_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='guestorder',
            name='payment_provider',
            field=models.CharField(default='FASTRR', max_length=30),
        ),
        migrations.AddField(
            model_name='guestorder',
            name='payment_session_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='guestorder',
            name='payment_transaction_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='guestorder',
            name='payment_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='breadth_cm',
            field=models.DecimalField(decimal_places=2, default=18, max_digits=7),
        ),
        migrations.AddField(
            model_name='product',
            name='height_cm',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
        ),
        migrations.AddField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='length_cm',
            field=models.DecimalField(decimal_places=2, default=24, max_digits=7),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_kg',
            field=models.DecimalField(decimal_places=3, default=0.3, max_digits=7),
        ),
        migrations.AlterField(
            model_name='guestorder',
            name='order_status',
            field=models.CharField(choices=[('AWAITING_PAYMENT', 'Awaiting Payment'), ('PAID', 'Paid'), ('PROCESSING', 'Processing'), ('READY_TO_SHIP', 'Ready To Ship'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='AWAITING_PAYMENT', max_length=40),
        ),
        migrations.AlterField(
            model_name='guestorder',
            name='payment_status',
            field=models.CharField(choices=[('NOT_CONFIGURED', 'Not Configured'), ('PENDING', 'Pending'), ('AUTHORIZED', 'Authorized'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUND_PENDING', 'Refund Pending'), ('REFUNDED', 'Refunded')], default='NOT_CONFIGURED', max_length=40),
        ),
        migrations.AlterField(
            model_name='guestorder',
            name='shipment_status',
            field=models.CharField(choices=[('NOT_CREATED', 'Not Created'), ('CREATION_PENDING', 'Creation Pending'), ('CREATION_FAILED', 'Creation Failed'), ('CREATED', 'Created'), ('AWB_ASSIGNED', 'Awb Assigned'), ('PICKUP_SCHEDULED', 'Pickup Scheduled'), ('SHIPPED', 'Shipped'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out For Delivery'), ('DELIVERED', 'Delivered'), ('DELAYED', 'Delayed'), ('UNDELIVERED', 'Undelivered'), ('RTO_INITIATED', 'Rto Initiated'), ('RTO_DELIVERED', 'Rto Delivered'), ('RETURNED', 'Returned')], default='NOT_CREATED', max_length=40),
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='FASTRR', max_length=30)),
                ('session_id', models.CharField(blank=True, max_length=120)),
                ('transaction_id', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(default='PENDING', max_length=40)),
                ('amount', models.PositiveIntegerField(help_text='Amount in INR paise')),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='store.guestorder')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_status', models.CharField(max_length=120)),
                ('normalized_status', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('event_time', models.DateTimeField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_events', to='store.guestorder')),
            ],
            options={
                'ordering': ['event_time'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('FASTRR', 'Fastrr'), ('SHIPROCKET', 'Shiprocket')], max_length=30)),
                ('event_key', models.CharField(max_length=128)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(default='RECEIVED', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_events', to='store.guestorder')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'event_key'), name='unique_provider_event')],
            },
        ),
    ]
