# Generated by Django 6.1 on 2026-08-21 06:58

from django.db import migrations, models


DEMO_SKUS = [
    'roots-nursery', 'roots-lkg', 'roots-ukg', 'oakwood-english-1', 'oakwood-english-2',
    'oakwood-english-3', 'numerica-1', 'numerica-2', 'numerica-3', 'explorer-science-3',
    'explorer-science-4', 'explorer-science-5', 'kalpvriksh-hindi-1', 'kalpvriksh-hindi-2',
    'kalpvriksh-hindi-3', 'social-world-3', 'social-world-4', 'social-world-5',
]


def deactivate_demo_catalogue(apps, schema_editor):
    Product = apps.get_model('store', 'Product')
    Product.objects.filter(sku__in=DEMO_SKUS).update(active=False, public_visibility=False)


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_guestorder_checkout_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='Textbooks', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='cover_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='cover_tone',
            field=models.CharField(default='cover-blue', max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='digital_features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='grade_range',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='imprint',
            field=models.CharField(default='Souvenir', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='isbn',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='level',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='public_visibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='series_code',
            field=models.SlugField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='series_slug',
            field=models.SlugField(default='', max_length=180),
        ),
        migrations.AddField(
            model_name='product',
            name='series_title',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AddField(
            model_name='product',
            name='stage',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='subject',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.RunPython(deactivate_demo_catalogue, migrations.RunPython.noop),
    ]
