# Generated by Django 6.1 on 2026-09-07 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_category_product_cover_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_url', models.URLField(blank=True, max_length=1000)),
                ('teacher_url', models.URLField(blank=True, max_length=1000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_resource', to='store.product')),
            ],
        ),
    ]
