# Generated by Django 6.1 on 2026-09-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_digitalresource'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('isbn', ''), _negated=True), fields=('isbn',), name='unique_nonempty_product_isbn'),
        ),
    ]
