# Generated by Django 6.1 on 2026-09-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_unique_nonempty_product_isbn'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalLearningRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=32, unique=True)),
                ('requester_role', models.CharField(max_length=60)),
                ('requester_name', models.CharField(max_length=160)),
                ('requester_designation', models.CharField(blank=True, max_length=160)),
                ('requester_organisation', models.CharField(blank=True, max_length=200)),
                ('school_name', models.CharField(max_length=200)),
                ('school_board', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=10)),
                ('state_code', models.CharField(max_length=4)),
                ('pin_code', models.CharField(max_length=6)),
                ('subject', models.CharField(max_length=120)),
                ('series_code', models.CharField(max_length=100)),
                ('series_title', models.CharField(max_length=180)),
                ('selected_books', models.JSONField(default=list)),
                ('resource_codes', models.JSONField(default=list)),
                ('purpose', models.CharField(max_length=160)),
                ('usage_details', models.TextField()),
                ('additional_details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('UNDER_REVIEW', 'Under review'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('FULFILLED', 'Fulfilled')], default='RECEIVED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
