"""
Django settings for Ecommerce project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-local-development-only')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() in {'1', 'true', 'yes'}

ALLOWED_HOSTS = [
    host.strip() for host in os.getenv('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')
    if host.strip()
]

CSRF_TRUSTED_ORIGINS = [
    origin.strip() for origin in os.getenv(
        'DJANGO_CSRF_TRUSTED_ORIGINS',
        'http://127.0.0.1:5173,http://localhost:5173',
    ).split(',') if origin.strip()
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'workflow',
    'store',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Ecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Ecommerce.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# Shiprocket Shipping API (set real values through environment variables).
SHIPROCKET_API_BASE_URL = os.getenv('SHIPROCKET_API_BASE_URL', 'https://apiv2.shiprocket.in/v1/external')
SHIPROCKET_API_EMAIL = os.getenv('SHIPROCKET_API_EMAIL', '')
SHIPROCKET_API_PASSWORD = os.getenv('SHIPROCKET_API_PASSWORD', '')
SHIPROCKET_PICKUP_LOCATION = os.getenv('SHIPROCKET_PICKUP_LOCATION', '')
SHIPROCKET_PICKUP_POSTCODE = os.getenv('SHIPROCKET_PICKUP_POSTCODE', '')
SHIPROCKET_WEBHOOK_TOKEN = os.getenv('SHIPROCKET_WEBHOOK_TOKEN', '')
SHIPROCKET_DEFAULT_PACKAGE_LENGTH_CM = float(os.getenv('SHIPROCKET_DEFAULT_PACKAGE_LENGTH_CM', '30'))
SHIPROCKET_DEFAULT_PACKAGE_BREADTH_CM = float(os.getenv('SHIPROCKET_DEFAULT_PACKAGE_BREADTH_CM', '22'))
SHIPROCKET_DEFAULT_PACKAGE_HEIGHT_CM = float(os.getenv('SHIPROCKET_DEFAULT_PACKAGE_HEIGHT_CM', '5'))

# Fastrr Checkout (values/endpoint come from the custom-stack onboarding kit).
FASTRR_CREATE_SESSION_URL = os.getenv('FASTRR_CREATE_SESSION_URL', '')
FASTRR_MERCHANT_ID = os.getenv('FASTRR_MERCHANT_ID', '')
FASTRR_PUBLIC_KEY = os.getenv('FASTRR_PUBLIC_KEY', '')
FASTRR_SECRET_KEY = os.getenv('FASTRR_SECRET_KEY', '')
FASTRR_WEBHOOK_SECRET = os.getenv('FASTRR_WEBHOOK_SECRET', '')
FASTRR_WEBHOOK_SIGNATURE_HEADER = os.getenv('FASTRR_WEBHOOK_SIGNATURE_HEADER', 'X-Fastrr-Signature')
FASTRR_SUCCESS_URL = os.getenv('FASTRR_SUCCESS_URL', 'http://127.0.0.1:5173/track-order')
FASTRR_CANCEL_URL = os.getenv('FASTRR_CANCEL_URL', 'http://127.0.0.1:5173/checkout')
