# Generated by Django 6.1 on 2026-08-14 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('account_type', models.CharField(choices=[('SCHOOL', 'School'), ('DISTRIBUTOR', 'Distributor')], max_length=20)),
                ('partner_key', models.CharField(max_length=40, unique=True)),
                ('state', models.CharField(max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('business_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_accounts', to=settings.AUTH_USER_MODEL)),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SCHOOL_ADMIN', 'School Admin'), ('SCHOOL_TEACHER', 'School Teacher'), ('DISTRIBUTOR_ADMIN', 'Distributor Admin'), ('BUSINESS_MANAGER', 'Business Manager'), ('SALES_REP', 'Sales Rep'), ('SALES_MANAGER', 'Sales Manager'), ('CATALOGUE_ADMIN', 'Catalogue Admin'), ('ORDER_OPERATIONS', 'Order Operations'), ('FINANCE', 'Finance'), ('DIGITAL_RESOURCE_ADMIN', 'Digital Resource Admin'), ('SUPER_ADMIN', 'Super Admin'), ('MANAGEMENT_SUPER_MASTER', 'Management Super Master'), ('TECH_MASTER', 'Tech Master'), ('PARTNER_NETWORK_ADMIN', 'Partner Network Admin'), ('COORDINATOR', 'Coordinator'), ('COORDINATOR_HEAD', 'Coordinator Head'), ('INVENTORY', 'Inventory'), ('INVENTORY_SUPERVISOR', 'Inventory Supervisor'), ('DISPATCH', 'Dispatch'), ('AUDITOR', 'Auditor')], max_length=40)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('warehouse_id', models.CharField(blank=True, max_length=40)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='workflow.account')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=32, unique=True)),
                ('request_type', models.CharField(choices=[('ORDER', 'Order'), ('SAMPLE', 'Sample')], max_length=10)),
                ('status', models.CharField(choices=[('SUBMITTED_TO_BM', 'Submitted To Bm'), ('PENDING_COORDINATOR_REVIEW', 'Pending Coordinator Review'), ('PENDING_HEAD_APPROVAL', 'Pending Head Approval'), ('CHANGES_REQUIRED', 'Changes Required'), ('REJECTED', 'Rejected'), ('READY_FOR_INVENTORY', 'Ready For Inventory'), ('PACKING_IN_PROGRESS', 'Packing In Progress'), ('PENDING_SUPERVISOR_VERIFICATION', 'Pending Supervisor Verification'), ('READY_FOR_DISPATCH', 'Ready For Dispatch'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered')], max_length=50)),
                ('lines', models.JSONField(default=list)),
                ('delivery_address', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('transporter', models.CharField(blank=True, max_length=120)),
                ('consignment_number', models.CharField(blank=True, max_length=120)),
                ('tracking_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='workflow.account')),
                ('assigned_bm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bm_requests', to=settings.AUTH_USER_MODEL)),
                ('assigned_coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinator_requests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60)),
                ('from_status', models.CharField(blank=True, max_length=50)),
                ('to_status', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='workflow.workflowrequest')),
            ],
        ),
    ]
